<?php

namespace Medelse\AriaBundle\Enum;

class LoanBlockedReasonEnum
{
    public const ARIA_SERVICE_PAYMENT_PAST_DUE = 'ARIA_SERVICE_PAYMENT_PAST_DUE';
    public const AWAITING_REPAYMENTS = 'AWAITING_REPAYMENTS';
    public const BENEFICIARY_CONTRACT_NOT_SIGNED = 'BENEFICIARY_CONTRACT_NOT_SIGNED';
    public const BENEFICIARY_INFORMATION_MISSING = 'BENEFICIARY_INFORMATION_MISSING';
    public const BENEFICIARY_INFORMATION_MISSING_MAIL = 'BENEFICIARY_INFORMATION_MISSING_MAIL';
    public const BENEFICIARY_INFORMATION_MISSING_PHONE = 'BENEFICIARY_INFORMATION_MISSING_PHONE';
    public const BENEFICIARY_INFORMATION_NOT_VALID = 'BENEFICIARY_INFORMATION_NOT_VALID';
    public const BENEFICIARY_INFORMATION_NOT_VALID_MAIL = 'BENEFICIARY_INFORMATION_NOT_VALID_MAIL';
    public const BENEFICIARY_INFORMATION_NOT_VALID_PHONE = 'BENEFICIARY_INFORMATION_NOT_VALID_PHONE';
    public const BENEFICIARY_INFORMATION_RISK_ISSUE = 'BENEFICIARY_INFORMATION_RISK_ISSUE';
    public const BENEFICIARY_KYC_CHECK_FAILED = 'BENEFICIARY_KYC_CHECK_FAILED';
    public const BENEFICIARY_KYC_MISSING = 'BENEFICIARY_KYC_MISSING';
    public const BENEFICIARY_KYC_NOT_VALID = 'BENEFICIARY_KYC_NOT_VALID';
    public const BENEFICIARY_LIMIT_MAX_OUTSTANDING_AMOUNT_OVERPASSED = 'BENEFICIARY_LIMIT_MAX_OUTSTANDING_AMOUNT_OVERPASSED';
    public const CREDIT_LIMIT_MAX_OUTSTANDING_AMOUNT_NOT_SUFFICIENT = 'CREDIT_LIMIT_MAX_OUTSTANDING_AMOUNT_NOT_SUFFICIENT';
    public const CREDIT_LIMIT_MAX_OUTSTANDING_AMOUNT_OVERPASSED = 'CREDIT_LIMIT_MAX_OUTSTANDING_AMOUNT_OVERPASSED';
    public const CREDIT_LIMIT_MISSING = 'CREDIT_LIMIT_MISSING';
    public const DEBTOR_CONTACT_MISSING = 'DEBTOR_CONTACT_MISSING';
    public const DEBTOR_CONTACT_MISSING_MAIL = 'DEBTOR_CONTACT_MISSING_MAIL';
    public const DEBTOR_CONTACT_MISSING_PHONE_NUMBER = 'DEBTOR_CONTACT_MISSING_PHONE_NUMBER';
    public const DEBTOR_CONTACT_MISSING_POSITION = 'DEBTOR_CONTACT_MISSING_POSITION';
    public const DEBTOR_CONTACT_NOT_VALID = 'DEBTOR_CONTACT_NOT_VALID';
    public const DEBTOR_CONTACT_NOT_VALID_MAIL = 'DEBTOR_CONTACT_NOT_VALID_MAIL';
    public const DEBTOR_CONTACT_NOT_VALID_PHONE_NUMBER = 'DEBTOR_CONTACT_NOT_VALID_PHONE_NUMBER';
    public const DEBTOR_CONTACT_NOT_VALID_POSITION = 'DEBTOR_CONTACT_NOT_VALID_POSITION';
    public const DEBTOR_IDENTIFIER_NOT_VALID = 'DEBTOR_IDENTIFIER_NOT_VALID';
    public const DEBTOR_INELIGIBLE = 'DEBTOR_INELIGIBLE';
    public const DEBTOR_NOT_VALID = 'DEBTOR_NOT_VALID';
    public const DEBTOR_NOT_VALID_NAME = 'DEBTOR_NOT_VALID_NAME';
    public const DEBTOR_RISK_ISSUE = 'DEBTOR_RISK_ISSUE';
    public const GUARANTOR_CONTRACT_NOT_SIGNED = 'GUARANTOR_CONTRACT_NOT_SIGNED';
    public const INVOICE_AMOUNT_NOT_VALID = 'INVOICE_AMOUNT_NOT_VALID';
    public const INVOICE_CURRENCY_NOT_VALID = 'INVOICE_CURRENCY_NOT_VALID';
    public const INVOICE_DATE_NOT_VALID = 'INVOICE_DATE_NOT_VALID';
    public const INVOICE_INFORMATION_RISK_ISSUE = 'INVOICE_INFORMATION_RISK_ISSUE';
    public const INVOICE_NOT_VALID = 'INVOICE_NOT_VALID';
    public const INVOICE_NUMBER_MISSING = 'INVOICE_NUMBER_MISSING';
    public const INVOICE_NUMBER_NOT_VALID = 'INVOICE_NUMBER_NOT_VALID';
    public const INVOICE_REPAYMENT_PERIOD_NOT_VALID = 'INVOICE_REPAYMENT_PERIOD_NOT_VALID';
    public const INVOICE_UNUSUAL_AMOUNT = 'INVOICE_UNUSUAL_AMOUNT';
    public const LOAN_AMOUNT_NOT_VALID = 'LOAN_AMOUNT_NOT_VALID';
    public const LOAN_ATTACHMENTS_MISSING = 'LOAN_ATTACHMENTS_MISSING';
    public const LOAN_ATTACHMENTS_NOT_VALID = 'LOAN_ATTACHMENTS_NOT_VALID';
    public const LOAN_INFORMATION_NOT_VALID = 'LOAN_INFORMATION_NOT_VALID';
    public const LOAN_INFORMATION_NOT_VALID_CURRENCY = 'LOAN_INFORMATION_NOT_VALID_CURRENCY';
    public const LOAN_INFORMATION_UNUSUAL_AMOUNT = 'LOAN_INFORMATION_UNUSUAL_AMOUNT';
    public const OTHER_REASON = 'OTHER_REASON';
}
