<?php

namespace Medelse\AriaBundle\Enum;

class LoanRefusalReasonEnum
{
    public const BENEFICIARY_KYC_NOT_VALID = 'BENEFICIARY_KYC_NOT_VALID';
    public const BENEFICIARY_NOT_ELIGIBLE = 'BENEFICIARY_NOT_ELIGIBLE';
    public const CREDIT_LIMIT_MAX_OUTSTANDING_AMOUNT_OVERPASSED = 'CREDIT_LIMIT_MAX_OUTSTANDING_AMOUNT_OVERPASSED';
    public const CREDIT_LIMIT_REFUSED = 'CREDIT_LIMIT_REFUSED';
    public const DEBTOR_NOT_ELIGIBLE = 'DEBTOR_NOT_ELIGIBLE';
    public const INVOICE_DATE_TOO_OLD = 'INVOICE_DATE_TOO_OLD';
    public const INVOICE_MISSING = 'INVOICE_MISSING';
    public const INVOICE_NOT_VALID = 'INVOICE_NOT_VALID';
    public const LATE_DEBTOR_REFUND = 'LATE_DEBTOR_REFUND';
    public const LOAN_CREATION_DATE_TOO_CLOSE_OR_EXCEEDS_INVOICE_DUE_DATE = 'LOAN_CREATION_DATE_TOO_CLOSE_OR_EXCEEDS_INVOICE_DUE_DATE';
    public const OTHER_REASON = 'OTHER_REASON';
}
